// Generated by gencpp from file planning_msgs/Octomap.msg
// DO NOT EDIT!


#ifndef PLANNING_MSGS_MESSAGE_OCTOMAP_H
#define PLANNING_MSGS_MESSAGE_OCTOMAP_H

#include <ros/service_traits.h>


#include <planning_msgs/OctomapRequest.h>
#include <planning_msgs/OctomapResponse.h>


namespace planning_msgs
{

struct Octomap
{

typedef OctomapRequest Request;
typedef OctomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Octomap
} // namespace planning_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning_msgs::Octomap > {
  static const char* value()
  {
    return "372c615313844175e948d7a83972d589";
  }

  static const char* value(const ::planning_msgs::Octomap&) { return value(); }
};

template<>
struct DataType< ::planning_msgs::Octomap > {
  static const char* value()
  {
    return "planning_msgs/Octomap";
  }

  static const char* value(const ::planning_msgs::Octomap&) { return value(); }
};


// service_traits::MD5Sum< ::planning_msgs::OctomapRequest> should match 
// service_traits::MD5Sum< ::planning_msgs::Octomap > 
template<>
struct MD5Sum< ::planning_msgs::OctomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning_msgs::Octomap >::value();
  }
  static const char* value(const ::planning_msgs::OctomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning_msgs::OctomapRequest> should match 
// service_traits::DataType< ::planning_msgs::Octomap > 
template<>
struct DataType< ::planning_msgs::OctomapRequest>
{
  static const char* value()
  {
    return DataType< ::planning_msgs::Octomap >::value();
  }
  static const char* value(const ::planning_msgs::OctomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning_msgs::OctomapResponse> should match 
// service_traits::MD5Sum< ::planning_msgs::Octomap > 
template<>
struct MD5Sum< ::planning_msgs::OctomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning_msgs::Octomap >::value();
  }
  static const char* value(const ::planning_msgs::OctomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning_msgs::OctomapResponse> should match 
// service_traits::DataType< ::planning_msgs::Octomap > 
template<>
struct DataType< ::planning_msgs::OctomapResponse>
{
  static const char* value()
  {
    return DataType< ::planning_msgs::Octomap >::value();
  }
  static const char* value(const ::planning_msgs::OctomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MSGS_MESSAGE_OCTOMAP_H
