// Generated by gencpp from file planning_msgs/PlannerService.msg
// DO NOT EDIT!


#ifndef PLANNING_MSGS_MESSAGE_PLANNERSERVICE_H
#define PLANNING_MSGS_MESSAGE_PLANNERSERVICE_H

#include <ros/service_traits.h>


#include <planning_msgs/PlannerServiceRequest.h>
#include <planning_msgs/PlannerServiceResponse.h>


namespace planning_msgs
{

struct PlannerService
{

typedef PlannerServiceRequest Request;
typedef PlannerServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlannerService
} // namespace planning_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning_msgs::PlannerService > {
  static const char* value()
  {
    return "e7bc30e0b0a79c76a0ad1244f8818092";
  }

  static const char* value(const ::planning_msgs::PlannerService&) { return value(); }
};

template<>
struct DataType< ::planning_msgs::PlannerService > {
  static const char* value()
  {
    return "planning_msgs/PlannerService";
  }

  static const char* value(const ::planning_msgs::PlannerService&) { return value(); }
};


// service_traits::MD5Sum< ::planning_msgs::PlannerServiceRequest> should match 
// service_traits::MD5Sum< ::planning_msgs::PlannerService > 
template<>
struct MD5Sum< ::planning_msgs::PlannerServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning_msgs::PlannerService >::value();
  }
  static const char* value(const ::planning_msgs::PlannerServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning_msgs::PlannerServiceRequest> should match 
// service_traits::DataType< ::planning_msgs::PlannerService > 
template<>
struct DataType< ::planning_msgs::PlannerServiceRequest>
{
  static const char* value()
  {
    return DataType< ::planning_msgs::PlannerService >::value();
  }
  static const char* value(const ::planning_msgs::PlannerServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning_msgs::PlannerServiceResponse> should match 
// service_traits::MD5Sum< ::planning_msgs::PlannerService > 
template<>
struct MD5Sum< ::planning_msgs::PlannerServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning_msgs::PlannerService >::value();
  }
  static const char* value(const ::planning_msgs::PlannerServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning_msgs::PlannerServiceResponse> should match 
// service_traits::DataType< ::planning_msgs::PlannerService > 
template<>
struct DataType< ::planning_msgs::PlannerServiceResponse>
{
  static const char* value()
  {
    return DataType< ::planning_msgs::PlannerService >::value();
  }
  static const char* value(const ::planning_msgs::PlannerServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MSGS_MESSAGE_PLANNERSERVICE_H
